[versions]
# kotlin
kotlin = "2.3.10"
kotlinxSerialization = "1.10.0"
nexus-publish = "2.0.0"

# database
hikariCp = "7.0.2"
postgreSql = "42.7.10"
mongodb = "5.6.4"
mysql = "9.6.0"
redis = "7.3.0"
mariadb = "3.5.7"
h2 = "2.4.240"

# polocloud
polocloud-i18n = "3.0.2"
polocloud-gradle-plugin = "3.0.0"

# logging
log4j = "2.25.3"

[libraries]
# database
hikariCp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikariCp" }
postgreSql = { group = "org.postgresql", name = "postgresql", version.ref = "postgreSql" }
mongodb = { group = "org.mongodb", name = "mongodb-driver-sync", version.ref = "mongodb" }
mysql = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql" }
redis = { group = "redis.clients", name = "jedis", version.ref = "redis" }
mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }

# logging
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

# polocloud
polocloud-i18n = { group = "de.polocloud", name = "polocloud-i18n", version.ref = "polocloud-i18n" }

[plugins]
polocloud-gradle-plugin = { id = "de.polocloud.gradle.plugin", version.ref = "polocloud-gradle-plugin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }

[bundles]
# database
database = ["hikariCp", "postgreSql"]
database-drivers = ["mongodb", "mysql", "redis", "mariadb", "h2"]
logging = ["log4j-api", "log4j-core", "log4j-slf4j"]
polocloud-common = ["polocloud-i18n", "kotlinx-serialization-json", "kotlin-reflect"]
